name: Generate Snake

on:
  schedule: # runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Files
        uses: Platane/snk@v3
        with:
          github_user_name: Abhinav5021
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
